"""adding foto field in pets

Revision ID: 230a00f25c7c
Revises: 72ffcdb0c39c
Create Date: 2026-06-21 15:42:47.411698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230a00f25c7c'
down_revision: Union[str, Sequence[str], None] = '72ffcdb0c39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'foto')
    # ### end Alembic commands ###
