"""adding JSON jam_tesedia

Revision ID: 5487573f4c90
Revises: cbcdd53970e9
Create Date: 2026-06-25 15:06:08.729333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5487573f4c90'
down_revision: Union[str, Sequence[str], None] = 'cbcdd53970e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paket_grooming', sa.Column('jam_tersedia', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paket_grooming', 'jam_tersedia')
    # ### end Alembic commands ###
