"""remove  username

Revision ID: 564f0877c0d8
Revises: da34e224eb5b
Create Date: 2026-05-24 23:29:47.049448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '564f0877c0d8'
down_revision: Union[str, Sequence[str], None] = 'da34e224eb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
