"""initial database

Revision ID: 5957a779c106
Revises: 
Create Date: 2026-05-24 20:12:28.155971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5957a779c106'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('email')
    )
    op.create_table('partners',
    sa.Column('id_partner', sa.Integer(), nullable=False),
    sa.Column('nama_partner', sa.String(length=255), nullable=False),
    sa.Column('jenis_partner', sa.Enum('GROOMING', 'KLINIK', 'ALL', name='jenispartner'), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_partner')
    )
    op.create_table('produk',
    sa.Column('id_produk', sa.Integer(), nullable=False),
    sa.Column('nama_produk', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_produk')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alamat',
    sa.Column('id_alamat', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('kota', sa.String(length=100), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('kode_pos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_alamat')
    )
    op.create_table('dokter',
    sa.Column('id_dokter', sa.Integer(), nullable=False),
    sa.Column('id_partner', sa.Integer(), nullable=False),
    sa.Column('nama_dokter', sa.String(length=255), nullable=False),
    sa.Column('spesialis', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_partner'], ['partners.id_partner'], ),
    sa.PrimaryKeyConstraint('id_dokter')
    )
    op.create_table('favorit',
    sa.Column('id_favorit', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_produk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_produk'], ['produk.id_produk'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorit')
    )
    op.create_table('membership',
    sa.Column('id_membership', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('tipe_membership', sa.Enum('BASIC', 'PREMIUM', 'VIP', name='tipemembership'), nullable=False),
    sa.Column('tanggal_berlaku', sa.Date(), nullable=False),
    sa.Column('tanggal_kedaluarsa', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_membership')
    )
    op.create_table('order_produk',
    sa.Column('id_order_produk', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('total_harga', sa.Float(), nullable=False),
    sa.Column('status_order', sa.Enum('MENUNGGU', 'DIPROSES', 'SELESAI', 'DIBATALKAN', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_order_produk')
    )
    op.create_table('paket_grooming',
    sa.Column('id_paket_grooming', sa.Integer(), nullable=False),
    sa.Column('id_partner', sa.Integer(), nullable=False),
    sa.Column('nama_paket_grooming', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_partner'], ['partners.id_partner'], ),
    sa.PrimaryKeyConstraint('id_paket_grooming')
    )
    op.create_table('pets',
    sa.Column('id_pet', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama_hewan', sa.String(length=255), nullable=False),
    sa.Column('jenis_hewan', sa.Enum('KUCING', 'ANJING', name='jenishewan'), nullable=False),
    sa.Column('umur', sa.Integer(), nullable=False),
    sa.Column('gender_hewan', sa.Enum('JANTAN', 'BETINA', name='genderhewan'), nullable=False),
    sa.Column('berat', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_pet')
    )
    op.create_table('booking_grooming',
    sa.Column('id_booking_grooming', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_pet', sa.Integer(), nullable=False),
    sa.Column('id_paket_grooming', sa.Integer(), nullable=False),
    sa.Column('tanggal_booking', sa.Date(), nullable=False),
    sa.Column('jam_booking', sa.Time(), nullable=False),
    sa.Column('status_booking', sa.Enum('MENUNGGU', 'SELESAI', 'DIBATALKAN', name='statusbooking'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paket_grooming'], ['paket_grooming.id_paket_grooming'], ),
    sa.ForeignKeyConstraint(['id_pet'], ['pets.id_pet'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_booking_grooming')
    )
    op.create_table('detail_order',
    sa.Column('id_detail_order', sa.Integer(), nullable=False),
    sa.Column('id_order_produk', sa.Integer(), nullable=False),
    sa.Column('id_produk', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_order_produk'], ['order_produk.id_order_produk'], ),
    sa.ForeignKeyConstraint(['id_produk'], ['produk.id_produk'], ),
    sa.PrimaryKeyConstraint('id_detail_order')
    )
    op.create_table('janji_temu',
    sa.Column('id_janji_temu', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_pet', sa.Integer(), nullable=False),
    sa.Column('id_dokter', sa.Integer(), nullable=False),
    sa.Column('tanggal_janji', sa.Date(), nullable=False),
    sa.Column('keluhan', sa.String(length=255), nullable=False),
    sa.Column('jam_janji', sa.Time(), nullable=False),
    sa.Column('status_janji', sa.Enum('MENUNGGU', 'SELESAI', 'DIBATALKAN', name='statusbooking'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], ),
    sa.ForeignKeyConstraint(['id_pet'], ['pets.id_pet'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_janji_temu')
    )
    op.create_table('pembayaran',
    sa.Column('id_pembayaran', sa.Integer(), nullable=False),
    sa.Column('id_order_produk', sa.Integer(), nullable=False),
    sa.Column('metode_pembayaran', sa.Enum('QRIS', 'GOPAY', 'TRANSFER_BANK', name='metodepembayaran'), nullable=False),
    sa.Column('status_pembayaran', sa.Enum('MENUNGGU', 'DIBAYAR', 'DIBATALKAN', name='statuspembayaran'), nullable=False),
    sa.ForeignKeyConstraint(['id_order_produk'], ['order_produk.id_order_produk'], ),
    sa.PrimaryKeyConstraint('id_pembayaran')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembayaran')
    op.drop_table('janji_temu')
    op.drop_table('detail_order')
    op.drop_table('booking_grooming')
    op.drop_table('pets')
    op.drop_table('paket_grooming')
    op.drop_table('order_produk')
    op.drop_table('membership')
    op.drop_table('favorit')
    op.drop_table('dokter')
    op.drop_table('alamat')
    op.drop_table('users')
    op.drop_table('produk')
    op.drop_table('partners')
    op.drop_table('admins')
    # ### end Alembic commands ###
