"""adding JSON jam_tesedia

Revision ID: 63e0875a425a
Revises: 5487573f4c90
Create Date: 2026-06-26 18:51:20.228047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e0875a425a'
down_revision: Union[str, Sequence[str], None] = '5487573f4c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_produk', sa.Column('midtrans_order_id', sa.String(length=255), nullable=True))
    op.add_column('pembayaran', sa.Column('midtrans_order_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pembayaran', 'midtrans_order_id')
    op.drop_column('order_produk', 'midtrans_order_id')
    # ### end Alembic commands ###
