"""adding type product

Revision ID: 6c3728643637
Revises: a7ab9973ac54
Create Date: 2026-06-21 08:31:58.524533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3728643637'
down_revision: Union[str, Sequence[str], None] = 'a7ab9973ac54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('tipe_produk', sa.Enum('MAKANAN', 'MAINAN', 'OBAT', 'AKSESORIS', name='tipeproduk'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produk', 'tipe_produk')
    # ### end Alembic commands ###
