"""adding delete product

Revision ID: 72ffcdb0c39c
Revises: 6c3728643637
Create Date: 2026-06-21 09:24:14.575607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ffcdb0c39c'
down_revision: Union[str, Sequence[str], None] = '6c3728643637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('status_produk', sa.Enum('TERSEDIA', 'HABIS', 'DIHAPUS', name='statusproduk'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produk', 'status_produk')
    # ### end Alembic commands ###
