"""add jam_operasional to partners

Revision ID: 7451d0c8b9c2
Revises: 63e0875a425a
Create Date: 2026-06-26 19:46:07.453839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7451d0c8b9c2'
down_revision: Union[str, Sequence[str], None] = '63e0875a425a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('jam_operasional', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'jam_operasional')
    # ### end Alembic commands ###
