"""email partner

Revision ID: 8f35cb84a387
Revises: d6961edc8080
Create Date: 2026-05-26 23:52:45.168941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f35cb84a387'
down_revision: Union[str, Sequence[str], None] = 'd6961edc8080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'partners', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partners', type_='unique')
    op.drop_column('partners', 'email')
    # ### end Alembic commands ###
