"""remove deskripsi'

Revision ID: be6370b6cf69
Revises: 564f0877c0d8
Create Date: 2026-05-25 06:54:57.613214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be6370b6cf69'
down_revision: Union[str, Sequence[str], None] = '564f0877c0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produk', 'deskripsi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('deskripsi', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
