"""add detail gooning

Revision ID: d6961edc8080
Revises: 82b7f36669ab
Create Date: 2026-05-26 23:44:50.370974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6961edc8080'
down_revision: Union[str, Sequence[str], None] = '82b7f36669ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paket_grooming', 'deskripsi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paket_grooming', sa.Column('deskripsi', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
