"""merge admin table into user

Revision ID: dd896a2d93fe
Revises: 5957a779c106
Create Date: 2026-05-24 22:55:55.610661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd896a2d93fe'
down_revision: Union[str, Sequence[str], None] = '5957a779c106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='admins')
    op.drop_table('admins')
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='roleuser'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('admins',
    sa.Column('id_admin', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('no_telepon', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('foto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_admin'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'admins', ['email'], unique=True)
    # ### end Alembic commands ###
