"""revisioning pembayaran,adding cart,adding cart item,adding receipt

Revision ID: dde666101894
Revises: 7744565fb0ab
Create Date: 2026-06-16 17:41:16.615477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dde666101894'
down_revision: Union[str, Sequence[str], None] = '7744565fb0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembayaran', sa.Column('id_user', sa.Integer(), nullable=False))
    op.add_column('pembayaran', sa.Column('id_booking_grooming', sa.Integer(), nullable=True))
    op.add_column('pembayaran', sa.Column('id_janji_temu', sa.Integer(), nullable=True))
    op.add_column('pembayaran', sa.Column('jumlah_bayar', sa.Float(), nullable=False))
    op.add_column('pembayaran', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('pembayaran', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('pembayaran', 'id_order_produk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'pembayaran', 'users', ['id_user'], ['id_user'])
    op.create_foreign_key(None, 'pembayaran', 'booking_grooming', ['id_booking_grooming'], ['id_booking_grooming'])
    op.create_foreign_key(None, 'pembayaran', 'janji_temu', ['id_janji_temu'], ['id_janji_temu'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pembayaran', type_='foreignkey')
    op.drop_constraint(None, 'pembayaran', type_='foreignkey')
    op.drop_constraint(None, 'pembayaran', type_='foreignkey')
    op.alter_column('pembayaran', 'id_order_produk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('pembayaran', 'updated_at')
    op.drop_column('pembayaran', 'created_at')
    op.drop_column('pembayaran', 'jumlah_bayar')
    op.drop_column('pembayaran', 'id_janji_temu')
    op.drop_column('pembayaran', 'id_booking_grooming')
    op.drop_column('pembayaran', 'id_user')
    # ### end Alembic commands ###
